folder="2013-07-08_15-46-06-profil-27"
standort=11
profil=27
anlage=1
ff="01"
classification=1
root_folder="E:/Eigene Dateien prescher/monica_simulations/runs/ascha/grundversuch/ff01/anlage-1/results/"
standortname="ascha"
data_folder ="E:/Eigene Dateien prescher/eva_messdaten/ascha/grundversuch/ff01/anlage-1"
