folder="2015-03-26_13-15-25-profil-22"
standort=11
profil=22
anlage=2
ff="03"
classification=1
root_folder="d:/Eigene Dateien prescher/monica_simulations/runs/ascha/grundversuch/ff03/anlage-2/results/"
standortname="ascha"
data_folder ="d:/Eigene Dateien prescher/eva_messdaten/ascha/grundversuch/ff03/anlage-2"
